version: '3.8'

services:
  # Django application service
  ppt_generator:
    image: python:3.12.5-slim
    container_name: ppt_generator
    build:
      context: ./ppt_generator
      dockerfile: Dockerfile
    command: bash -c "pip install -r /app/requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ppt_generator:/app
    ports:
      - "8000:8000"
    depends_on:
      - ppt_db
      - redis
    env_file:
      - .env  # Load environment variables from .env file

  # PostgreSQL database service
  ppt_db:
    image: postgres:latest
    container_name: ppt_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose the PostgreSQL port

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose the Redis port

volumes:
  postgres_data:
    driver: local
